spring:
  application:
    name: hello-server

server:
  port: 8071

eureka:
  client:
    eureka-server-connect-timeout-seconds: 0
    service-url: http://localhost:8070/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost